apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: kubernetes-cluster-deployment
spec:
  selector:
    matchLabels:
      app: kubernetes-cluster
  replicas: 3 
  template:
    metadata:
      labels:
        app: kubernetes-cluster
    spec:
      containers:
      - name: kubernetes-cluster-container 
        image: buildapp/webapp
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: kubernetes-cluster-service
spec:
  type: NodePort
  selector:
    app: kubernetes-cluster
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32000
